version: 2
jobs:
  build:
    working_directory: ~/source
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx4608m
    steps:
      - checkout
      - run:
          name: Init Environment
          command: |
            echo "" >> gradle.properties;
            echo "key_store_password=$KEY_STORE_PASS" >> gradle.properties;
            openssl aes-256-cbc -d -a -in service_account.json.enc -out app/service_account.json -k $KEY_STORE_PASS || true;
            openssl aes-256-cbc -d -a -in release_key.jks.enc -out app/release_key.jks -k $KEY_STORE_PASS || true;
      - restore_cache:
          key: "dependencies-cache"
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: "dependencies-cache"
      - run:
          name: Test - Build - Publish
          command: ./.circleci/test_build_publish.sh
      - store_artifacts:
          path: artifacts
